UPDATE_STALE_AGE_SEC = 60

SUBSCRIPTION_CACHE_SUBSCRIBED_MAXSIZE = 200_000
SUBSCRIPTION_CACHE_SUBSCRIBED_TTL_SEC = 300
SUBSCRIPTION_CACHE_UNSUBSCRIBED_MAXSIZE = 100_000
SUBSCRIPTION_CACHE_UNSUBSCRIBED_TTL_SEC = 60

CONCURRENCY_REJECT_NOTICE_CACHE_MAXSIZE = 100_000
CONCURRENCY_REJECT_NOTICE_TTL_SEC = 5

THROTTLE_CACHE_MAXSIZE = 50_000
THROTTLE_CACHE_TTL_SEC = 1.0
THROTTLE_NOTICE_CACHE_MAXSIZE = 50_000
THROTTLE_NOTICE_TTL_SEC = 1.0

START_UTM_EXISTS_CACHE_MAXSIZE = 20_000
START_UTM_EXISTS_TTL_SEC = 300

USER_SNAPSHOT_CACHE_MAXSIZE = 150_000
USER_SNAPSHOT_CACHE_TTL_SEC = 30
USER_EXISTS_CACHE_MAXSIZE = 150_000
USER_EXISTS_CACHE_TTL_SEC = 60

BAN_CACHE_MAXSIZE = 50_000
BAN_CACHE_TTL_SEC = 30

DIRECT_START_USER_EXISTS_CACHE_MAXSIZE = 50_000
DIRECT_START_USER_EXISTS_CACHE_TTL_SEC = 20

ADMIN_CACHE_MAXSIZE = 10_000
ADMIN_CACHE_TTL_SEC = 60

REMNAWAVE_SERVER_CACHE_MAXSIZE = 50_000
REMNAWAVE_SERVER_CACHE_TTL_SEC = 300
REMNAWAVE_PROFILE_CACHE_MAXSIZE = 200_000
REMNAWAVE_PROFILE_CACHE_TTL_SEC = 20
REMNAWAVE_PROFILE_TIMEOUT_SEC = 3.0
REMNAWAVE_ACTION_TIMEOUT_SEC = 5.0
REMNAWAVE_MAX_CONCURRENCY = 20

RUNTIME_CONFIG_SYNC_PULL_INTERVAL_SEC = 1.0
RUNTIME_CONFIG_SYNC_TTL_SEC = 86_400

SUBSCRIPTION_RESPONSE_CACHE_TTL_SEC = 20
SUBSCRIPTION_HANDLER_CONCURRENCY = 80

SERVERS_CACHE_TTL_SEC = 60
TARIFF_BY_ID_CACHE_TTL_SEC = 120
TARIFFS_FOR_CLUSTER_CACHE_TTL_SEC = 120
